# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import DeviceService
from ._models_py3 import DeviceServiceCheckNameAvailabilityParameters
from ._models_py3 import DeviceServiceDescriptionListResult
from ._models_py3 import DeviceServiceNameAvailabilityInfo
from ._models_py3 import ErrorDetails
from ._models_py3 import ErrorDetailsError
from ._models_py3 import OperationDisplayInfo
from ._models_py3 import OperationEntity
from ._models_py3 import OperationListResult
from ._models_py3 import ProxyResource
from ._models_py3 import Resource
from ._models_py3 import TrackedResource

from ._device_services_enums import ServiceNameUnavailabilityReason
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "DeviceService",
    "DeviceServiceCheckNameAvailabilityParameters",
    "DeviceServiceDescriptionListResult",
    "DeviceServiceNameAvailabilityInfo",
    "ErrorDetails",
    "ErrorDetailsError",
    "OperationDisplayInfo",
    "OperationEntity",
    "OperationListResult",
    "ProxyResource",
    "Resource",
    "TrackedResource",
    "ServiceNameUnavailabilityReason",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
