# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AccessProfileType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Name which contains the role of the kubeconfig.
    """

    CLUSTER_USER = "clusterUser"

class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource.
    """

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"

class Distro(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents a supported Fabric/Infra. (AKSEdge etc...).
    """

    AKS_EDGE = "AKSEdge"

class Provider(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Information about the connected appliance.
    """

    VM_WARE = "VMWare"
    HCI = "HCI"
    SCVMM = "SCVMM"

class ResourceIdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The identity type.
    """

    SYSTEM_ASSIGNED = "SystemAssigned"
    NONE = "None"

class Status(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Appliance’s health and state of connection to on-prem
    """

    WAITING_FOR_HEARTBEAT = "WaitingForHeartbeat"
    VALIDATING = "Validating"
    CONNECTED = "Connected"
    RUNNING = "Running"
