# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from typing import Any, Optional, TYPE_CHECKING

from msrest import Deserializer, Serializer

from azure.mgmt.core import AsyncARMPipelineClient
from azure.profiles import KnownProfiles, ProfileDefinition
from azure.profiles.multiapiclient import MultiApiClientMixin

from ._configuration import ApplicationClientConfiguration
from ._operations_mixin import ApplicationClientOperationsMixin

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials import TokenCredential
    from azure.core.credentials_async import AsyncTokenCredential

class _SDKClient(object):
    def __init__(self, *args, **kwargs):
        """This is a fake class to support current implemetation of MultiApiClientMixin."
        Will be removed in final version of multiapi azure-core based client
        """
        pass

class ApplicationClient(ApplicationClientOperationsMixin, MultiApiClientMixin, _SDKClient):
    """ARM applications.

    This ready contains multiple API versions, to help you deal with all of the Azure clouds
    (Azure Stack, Azure Government, Azure China, etc.).
    By default, it uses the latest API version available on public Azure.
    For production, you should stick to a particular api-version and/or profile.
    The profile sets a mapping between an operation group and its API version.
    The api-version parameter sets the default API version if the operation
    group is not described in the profile.

    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :param subscription_id: The ID of the target subscription.
    :type subscription_id: str
    :param api_version: API version to use if no profile is provided, or if missing in profile.
    :type api_version: str
    :param base_url: Service URL
    :type base_url: str
    :param profile: A profile definition, from KnownProfiles to dict.
    :type profile: azure.profiles.KnownProfiles
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    DEFAULT_API_VERSION = '2021-07-01'
    _PROFILE_TAG = "azure.mgmt.managedapplication.ApplicationClient"
    LATEST_PROFILE = ProfileDefinition({
        _PROFILE_TAG: {
            None: DEFAULT_API_VERSION,
        }},
        _PROFILE_TAG + " latest"
    )

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        subscription_id: str,
        api_version: Optional[str] = None,
        base_url: str = "https://management.azure.com",
        profile: KnownProfiles = KnownProfiles.default,
        **kwargs  # type: Any
    ) -> None:
        self._config = ApplicationClientConfiguration(credential, subscription_id, **kwargs)
        self._client = AsyncARMPipelineClient(base_url=base_url, config=self._config, **kwargs)
        super(ApplicationClient, self).__init__(
            api_version=api_version,
            profile=profile
        )

    @classmethod
    def _models_dict(cls, api_version):
        return {k: v for k, v in cls.models(api_version).__dict__.items() if isinstance(v, type)}

    @classmethod
    def models(cls, api_version=DEFAULT_API_VERSION):
        """Module depends on the API version:

           * 2017-09-01: :mod:`v2017_09_01.models<azure.mgmt.managedapplication.v2017_09_01.models>`
           * 2017-12-01: :mod:`v2017_12_01.models<azure.mgmt.managedapplication.v2017_12_01.models>`
           * 2018-02-01: :mod:`v2018_02_01.models<azure.mgmt.managedapplication.v2018_02_01.models>`
           * 2018-03-01: :mod:`v2018_03_01.models<azure.mgmt.managedapplication.v2018_03_01.models>`
           * 2018-06-01: :mod:`v2018_06_01.models<azure.mgmt.managedapplication.v2018_06_01.models>`
           * 2018-09-01-preview: :mod:`v2018_09_01_preview.models<azure.mgmt.managedapplication.v2018_09_01_preview.models>`
           * 2019-07-01: :mod:`v2019_07_01.models<azure.mgmt.managedapplication.v2019_07_01.models>`
           * 2020-08-21-preview: :mod:`v2020_08_21_preview.models<azure.mgmt.managedapplication.v2020_08_21_preview.models>`
           * 2021-02-01-preview: :mod:`v2021_02_01_preview.models<azure.mgmt.managedapplication.v2021_02_01_preview.models>`
           * 2021-07-01: :mod:`v2021_07_01.models<azure.mgmt.managedapplication.v2021_07_01.models>`
        """
        if api_version == '2017-09-01':
            from ..v2017_09_01 import models
            return models
        elif api_version == '2017-12-01':
            from ..v2017_12_01 import models
            return models
        elif api_version == '2018-02-01':
            from ..v2018_02_01 import models
            return models
        elif api_version == '2018-03-01':
            from ..v2018_03_01 import models
            return models
        elif api_version == '2018-06-01':
            from ..v2018_06_01 import models
            return models
        elif api_version == '2018-09-01-preview':
            from ..v2018_09_01_preview import models
            return models
        elif api_version == '2019-07-01':
            from ..v2019_07_01 import models
            return models
        elif api_version == '2020-08-21-preview':
            from ..v2020_08_21_preview import models
            return models
        elif api_version == '2021-02-01-preview':
            from ..v2021_02_01_preview import models
            return models
        elif api_version == '2021-07-01':
            from ..v2021_07_01 import models
            return models
        raise ValueError("API version {} is not available".format(api_version))

    @property
    def application_definitions(self):
        """Instance depends on the API version:

           * 2017-09-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2017_09_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2017-12-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2017_12_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2018-02-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2018_02_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2018-03-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2018_03_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2018-06-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2018_06_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2018-09-01-preview: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2018_09_01_preview.aio.operations.ApplicationDefinitionsOperations>`
           * 2019-07-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2019_07_01.aio.operations.ApplicationDefinitionsOperations>`
           * 2020-08-21-preview: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2020_08_21_preview.aio.operations.ApplicationDefinitionsOperations>`
           * 2021-02-01-preview: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2021_02_01_preview.aio.operations.ApplicationDefinitionsOperations>`
           * 2021-07-01: :class:`ApplicationDefinitionsOperations<azure.mgmt.managedapplication.v2021_07_01.aio.operations.ApplicationDefinitionsOperations>`
        """
        api_version = self._get_api_version('application_definitions')
        if api_version == '2017-09-01':
            from ..v2017_09_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2017-12-01':
            from ..v2017_12_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2018-02-01':
            from ..v2018_02_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2018-03-01':
            from ..v2018_03_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2018-06-01':
            from ..v2018_06_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2018-09-01-preview':
            from ..v2018_09_01_preview.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2019-07-01':
            from ..v2019_07_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2020-08-21-preview':
            from ..v2020_08_21_preview.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2021-02-01-preview':
            from ..v2021_02_01_preview.aio.operations import ApplicationDefinitionsOperations as OperationClass
        elif api_version == '2021-07-01':
            from ..v2021_07_01.aio.operations import ApplicationDefinitionsOperations as OperationClass
        else:
            raise ValueError("API version {} does not have operation group 'application_definitions'".format(api_version))
        return OperationClass(self._client, self._config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def applications(self):
        """Instance depends on the API version:

           * 2017-09-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2017_09_01.aio.operations.ApplicationsOperations>`
           * 2017-12-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2017_12_01.aio.operations.ApplicationsOperations>`
           * 2018-02-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2018_02_01.aio.operations.ApplicationsOperations>`
           * 2018-03-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2018_03_01.aio.operations.ApplicationsOperations>`
           * 2018-06-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2018_06_01.aio.operations.ApplicationsOperations>`
           * 2018-09-01-preview: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2018_09_01_preview.aio.operations.ApplicationsOperations>`
           * 2019-07-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2019_07_01.aio.operations.ApplicationsOperations>`
           * 2020-08-21-preview: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2020_08_21_preview.aio.operations.ApplicationsOperations>`
           * 2021-02-01-preview: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2021_02_01_preview.aio.operations.ApplicationsOperations>`
           * 2021-07-01: :class:`ApplicationsOperations<azure.mgmt.managedapplication.v2021_07_01.aio.operations.ApplicationsOperations>`
        """
        api_version = self._get_api_version('applications')
        if api_version == '2017-09-01':
            from ..v2017_09_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2017-12-01':
            from ..v2017_12_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2018-02-01':
            from ..v2018_02_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2018-03-01':
            from ..v2018_03_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2018-06-01':
            from ..v2018_06_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2018-09-01-preview':
            from ..v2018_09_01_preview.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2019-07-01':
            from ..v2019_07_01.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2020-08-21-preview':
            from ..v2020_08_21_preview.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2021-02-01-preview':
            from ..v2021_02_01_preview.aio.operations import ApplicationsOperations as OperationClass
        elif api_version == '2021-07-01':
            from ..v2021_07_01.aio.operations import ApplicationsOperations as OperationClass
        else:
            raise ValueError("API version {} does not have operation group 'applications'".format(api_version))
        return OperationClass(self._client, self._config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    @property
    def jit_requests(self):
        """Instance depends on the API version:

           * 2018-03-01: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2018_03_01.aio.operations.JitRequestsOperations>`
           * 2018-06-01: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2018_06_01.aio.operations.JitRequestsOperations>`
           * 2018-09-01-preview: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2018_09_01_preview.aio.operations.JitRequestsOperations>`
           * 2019-07-01: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2019_07_01.aio.operations.JitRequestsOperations>`
           * 2020-08-21-preview: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2020_08_21_preview.aio.operations.JitRequestsOperations>`
           * 2021-02-01-preview: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2021_02_01_preview.aio.operations.JitRequestsOperations>`
           * 2021-07-01: :class:`JitRequestsOperations<azure.mgmt.managedapplication.v2021_07_01.aio.operations.JitRequestsOperations>`
        """
        api_version = self._get_api_version('jit_requests')
        if api_version == '2018-03-01':
            from ..v2018_03_01.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2018-06-01':
            from ..v2018_06_01.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2018-09-01-preview':
            from ..v2018_09_01_preview.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2019-07-01':
            from ..v2019_07_01.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2020-08-21-preview':
            from ..v2020_08_21_preview.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2021-02-01-preview':
            from ..v2021_02_01_preview.aio.operations import JitRequestsOperations as OperationClass
        elif api_version == '2021-07-01':
            from ..v2021_07_01.aio.operations import JitRequestsOperations as OperationClass
        else:
            raise ValueError("API version {} does not have operation group 'jit_requests'".format(api_version))
        return OperationClass(self._client, self._config, Serializer(self._models_dict(api_version)), Deserializer(self._models_dict(api_version)))

    async def close(self):
        await self._client.close()
    async def __aenter__(self):
        await self._client.__aenter__()
        return self
    async def __aexit__(self, *exc_details):
        await self._client.__aexit__(*exc_details)
