# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class Kind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Responsibility role under which this Managed Network Group will be created."""

    CONNECTIVITY = "Connectivity"


class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Provisioning state of the ManagedNetwork resource."""

    UPDATING = "Updating"
    DELETING = "Deleting"
    FAILED = "Failed"
    SUCCEEDED = "Succeeded"


class Type(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Gets or sets the connectivity type of a network structure policy."""

    HUB_AND_SPOKE_TOPOLOGY = "HubAndSpokeTopology"
    MESH_TOPOLOGY = "MeshTopology"
