# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import AllSavingsBenefitDetails
from ._models_py3 import AllSavingsList
from ._models_py3 import BenefitRecommendationModel
from ._models_py3 import BenefitRecommendationProperties
from ._models_py3 import BenefitRecommendationsListResult
from ._models_py3 import BenefitResource
from ._models_py3 import BenefitUtilizationSummariesListResult
from ._models_py3 import BenefitUtilizationSummary
from ._models_py3 import BenefitUtilizationSummaryProperties
from ._models_py3 import BlobInfo
from ._models_py3 import CheckNameAvailabilityRequest
from ._models_py3 import CheckNameAvailabilityResponse
from ._models_py3 import CostDetailsOperationResults
from ._models_py3 import CostDetailsTimePeriod
from ._models_py3 import CostManagementOperation
from ._models_py3 import ErrorDetails
from ._models_py3 import ErrorResponse
from ._models_py3 import FileDestination
from ._models_py3 import GenerateCostDetailsReportErrorResponse
from ._models_py3 import GenerateCostDetailsReportRequestDefinition
from ._models_py3 import IncludedQuantityUtilizationSummary
from ._models_py3 import IncludedQuantityUtilizationSummaryProperties
from ._models_py3 import NotificationProperties
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import ProxyResource
from ._models_py3 import RecommendationUsageDetails
from ._models_py3 import Resource
from ._models_py3 import SavingsPlanUtilizationSummary
from ._models_py3 import SavingsPlanUtilizationSummaryProperties
from ._models_py3 import ScheduleProperties
from ._models_py3 import ScheduledAction
from ._models_py3 import ScheduledActionListResult
from ._models_py3 import ScheduledActionProxyResource
from ._models_py3 import SharedScopeBenefitRecommendationProperties
from ._models_py3 import SingleScopeBenefitRecommendationProperties
from ._models_py3 import SystemData

from ._cost_management_client_enums import ActionType
from ._cost_management_client_enums import BenefitKind
from ._cost_management_client_enums import CheckNameAvailabilityReason
from ._cost_management_client_enums import CostDetailsDataFormat
from ._cost_management_client_enums import CostDetailsMetricType
from ._cost_management_client_enums import CostDetailsStatusType
from ._cost_management_client_enums import CreatedByType
from ._cost_management_client_enums import DaysOfWeek
from ._cost_management_client_enums import FileFormat
from ._cost_management_client_enums import Grain
from ._cost_management_client_enums import GrainParameter
from ._cost_management_client_enums import LookBackPeriod
from ._cost_management_client_enums import Origin
from ._cost_management_client_enums import ScheduleFrequency
from ._cost_management_client_enums import ScheduledActionKind
from ._cost_management_client_enums import ScheduledActionStatus
from ._cost_management_client_enums import Scope
from ._cost_management_client_enums import Term
from ._cost_management_client_enums import WeeksOfMonth
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AllSavingsBenefitDetails",
    "AllSavingsList",
    "BenefitRecommendationModel",
    "BenefitRecommendationProperties",
    "BenefitRecommendationsListResult",
    "BenefitResource",
    "BenefitUtilizationSummariesListResult",
    "BenefitUtilizationSummary",
    "BenefitUtilizationSummaryProperties",
    "BlobInfo",
    "CheckNameAvailabilityRequest",
    "CheckNameAvailabilityResponse",
    "CostDetailsOperationResults",
    "CostDetailsTimePeriod",
    "CostManagementOperation",
    "ErrorDetails",
    "ErrorResponse",
    "FileDestination",
    "GenerateCostDetailsReportErrorResponse",
    "GenerateCostDetailsReportRequestDefinition",
    "IncludedQuantityUtilizationSummary",
    "IncludedQuantityUtilizationSummaryProperties",
    "NotificationProperties",
    "Operation",
    "OperationDisplay",
    "OperationListResult",
    "ProxyResource",
    "RecommendationUsageDetails",
    "Resource",
    "SavingsPlanUtilizationSummary",
    "SavingsPlanUtilizationSummaryProperties",
    "ScheduleProperties",
    "ScheduledAction",
    "ScheduledActionListResult",
    "ScheduledActionProxyResource",
    "SharedScopeBenefitRecommendationProperties",
    "SingleScopeBenefitRecommendationProperties",
    "SystemData",
    "ActionType",
    "BenefitKind",
    "CheckNameAvailabilityReason",
    "CostDetailsDataFormat",
    "CostDetailsMetricType",
    "CostDetailsStatusType",
    "CreatedByType",
    "DaysOfWeek",
    "FileFormat",
    "Grain",
    "GrainParameter",
    "LookBackPeriod",
    "Origin",
    "ScheduleFrequency",
    "ScheduledActionKind",
    "ScheduledActionStatus",
    "Scope",
    "Term",
    "WeeksOfMonth",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
