# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs."""

    INTERNAL = "Internal"


class AuthorizationStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Determines the authorization status of requests."""

    #: Requests authorized successfully
    AUTHORIZED = "Authorized"
    #: Requests returned NotFound response
    NOT_FOUND = "NotFound"
    #: Requests returned other error response
    ERROR = "Error"


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource."""

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"


class DockerfileGenerationMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The mode of generation to be used for generating Dockerfiles."""

    #: Dockerfiles will be generated
    ENABLED = "enabled"
    #: Dockerfiles will not be generated
    DISABLED = "disabled"


class GenerationLanguage(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The programming language used."""

    #: clojure language
    CLOJURE = "clojure"
    #: csharp language
    CSHARP = "csharp"
    #: erlang language
    ERLANG = "erlang"
    #: go language
    GO = "go"
    #: gomodule language
    GOMODULE = "gomodule"
    #: gradle language
    GRADLE = "gradle"
    #: java language
    JAVA = "java"
    #: javascript language
    JAVASCRIPT = "javascript"
    #: php language
    PHP = "php"
    #: python language
    PYTHON = "python"
    #: ruby language
    RUBY = "ruby"
    #: rust language
    RUST = "rust"
    #: swift language
    SWIFT = "swift"


class ManifestGenerationMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The mode of generation to be used for generating Dockerfiles."""

    #: Manifests will be generated
    ENABLED = "enabled"
    #: Manifests will not be generated
    DISABLED = "disabled"


class ManifestType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Determines the type of manifests within the repository."""

    #: Manifests using helm
    HELM = "helm"
    #: Standard Kubernetes manifests
    KUBE = "kube"
    #: Manifests using kustomize
    KUSTOMIZE = "kustomize"


class Origin(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
    logs UX. Default value is "user,system".
    """

    USER = "user"
    SYSTEM = "system"
    USER_SYSTEM = "user,system"


class PullRequestStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The status of the Pull Request submitted against the users repository."""

    #: Pull Request state unknown.
    UNKNOWN = "unknown"
    #: Pull Request submitted to repository.
    SUBMITTED = "submitted"
    #: Pull Request merged into repository.
    MERGED = "merged"
    #: Workflow no longer found within repository.
    REMOVED = "removed"
